/*\
title: $:/plugins/cdr/markdown-more/toc-widget.js
type: application/javascript
module-type: widget

Creates a table of contents section from the content within the widget.
\*/

(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

var Widget = require("$:/core/modules/widgets/widget.js").widget;

class TocWidget extends Widget {
	constructor(parseTreeNode,options) {
		super(parseTreeNode,options);
	}

	// Render this widget into the DOM
	render(parent,nextSibling) {
		this.parentDomNode = parent;
		this.computeAttributes();
		this.execute();

		let toc = [];
		const qualifier = this.getStateQualifier();
		const bodyNode = this.document.createElement("div");

		this.renderChildren(bodyNode,null);

		if(this.enableTOC) {
			toc = scanTOC(bodyNode,this.depth,qualifier);
		}

		if(toc.length > 0) {
			const domNode = this.document.createElement("div");
			const sideNode = this.document.createElement("div");
			const navNode = this.document.createElement("nav");

			domNode.className  = "md-container";
			bodyNode.className = "md-main";
			sideNode.classList = "md-aside";
			navNode.className  = "table-of-contents";

			renderTOC.call(this,navNode,toc);

			sideNode.appendChild(navNode);
			domNode.appendChild(sideNode);
			domNode.appendChild(bodyNode);
			parent.insertBefore(domNode,nextSibling);

			/** @type {HTMLElement[]} */
			(this.domNodes).push(domNode);
		} else {
			while(bodyNode.childNodes.length > 0) {
				// child is removed from bodyNode.childNodes automatically when it's inserted into parent
				parent.insertBefore(bodyNode.childNodes[0],nextSibling);
				if(bodyNode.isTiddlyWikiFakeDom) {
					bodyNode.children.shift();
				}
			}
		}
	}

	execute() {
		this.depth = parseInt(this.getAttribute("depth","3"),10);
		if(Number.isNaN(this.depth) || this.depth < 0) {
			this.depth = 0;
		}
		this.enableTOC = this.getAttribute("enable","yes") === "yes";

		// Construct the child widgets
		this.makeChildWidgets();
	}

	refresh(changedTiddlers) {
		const changedAttributes = this.computeAttributes();
		const refresh = this.refreshChildren(changedTiddlers) || Object.keys(changedAttributes).length > 0;

		if(refresh) {
			this.refreshSelf();
		}
		return refresh;
	}

	// Overrides the default: created TOC nodes may have been removed already if there are nested
  	// <$toc> widgets.
	removeChildDomNodes() {
		const domNodes = /** @type {HTMLElement[]} */ (this.domNodes);

		if(domNodes.length > 0) {
			$tw.utils.each(this.domNodes,function(domNode) {
				if(domNode.parentNode) {
					domNode.parentNode.removeChild(domNode);
				}
			});
			this.domNodes = [];
		} else {
			$tw.utils.each(this.children,function(childWidget) {
				childWidget.removeChildDomNodes();
			});
		}
	}

	// Find the first DOM node generated by a widget or its children
	findFirstDomNode() {
		const domNodes = /** @type {HTMLElement[]} */ (this.domNodes);

		// Return the first dom node of this widget, if we've got one
		if(domNodes.length > 0 && domNodes[0].parentNode) {
			return domNodes[0];
		}
		// Otherwise, recursively call our children
		for(let t=0; t</** @type {Widget[]} */ (this.children).length; t++) {
			const domNode =/** @type {Widget[]} */ (this.children)[t].findFirstDomNode();
			if(domNode) {
				return domNode;
			}
		}
		return null;
	};
}

function scanTOC(startNode,maxDepth,qualifier) {
	if(startNode.isTiddlyWikiFakeDom) { return []; }

	const layout = []; // list of H<n> objects
	const state = { id: 0, curLevel: 0 };
	const stack = [startNode];
	let node;

	// pre-order traversal of DOM tree
  	while(stack.length > 0) {
		node = stack.pop();

		if(isHeading(node.tagName)) {
			processHnNode(node,layout,state,maxDepth,qualifier);
		} else if(node.classList.contains("md-container")) {
			// encounters a nested TOC
			const mainNode = node.querySelector(":scope > .md-main");
			if(mainNode) {
				let sibling = node.nextSibling;
				while(mainNode.childNodes.length > 0) {
					stack.push(mainNode.lastChild);
					node.parentNode.insertBefore(mainNode.lastChild,sibling);
					sibling = (sibling ? sibling.previousSibling : node.parentNode.lastChild);
				}
				node.parentNode.removeChild(node);
				continue;
			}
		}

		for(let i=node.children.length-1; i >= 0; i--) {
			stack.push(node.children[i]);
		}
  	}
	return layout;
}

function isHeading(tag) {
	if(tag.length !== 2 || tag[0] !== "H") { return false; }

	var n = parseInt(tag[1],10);
	return n >= 1 && n <= 6;
}

// maxDepth is the maximum heading level to display.
// level corresponds to h<n>.
function processHnNode(node,layout,state,maxDepth,qualifier) {
	var level = parseInt(node.tagName[1],10);

	if(level > maxDepth) { return; }

	const anchor = `#topic${state.id++}-${qualifier}`;
	const heading = { level: level, text: node.textContent, anchor: anchor };

	$tw.utils.addClass(node,"anchor-item");
	node.setAttribute("id",anchor);

	state.curLevel = level;
	layout.push(heading);
}

/**
 * @this {TocWidget}
 */
function renderTOC(navNode,toc) {
	if(!toc || toc.length <= 0) {
		return;
	}
	var minTocLevel = Infinity;
	for(let i=0; i< toc.length; i++) {
		if(toc[i].level < minTocLevel) {
			minTocLevel = toc[i].level;
		}
	}

	const stack = [ {domNode: navNode, level: 0} ];
	// biome-ignore lint/style/useSingleVarDeclarator: keep layout compact
	let node, listNode, itemNode, linkNode, spanNode;

	for(let i=0; i < toc.length; i++) {
		const entry = toc[i];

		while(stack.length > 0 && stack[stack.length - 1].level >= entry.level) {
			stack.pop();
		}

		const top = stack[stack.length - 1];
		let prevLevel;
		let parent;

		prevLevel = top.level;
		parent = top.domNode;

		while(entry.level > prevLevel) {
			if(prevLevel === 0){
				// allow initial top level heading to be any h<n>
				//prevLevel = entry.level;
				prevLevel = minTocLevel;
				//prevLevel += 1;
			} else {
				prevLevel+=1;
			}
			listNode = this.document.createElement("ol");
			$tw.utils.addClass(listNode,"toc-list");
			parent.appendChild(listNode);

			node = { domNode: listNode, level: prevLevel };
			stack.push(node);
			parent = listNode;
		}
		// create an list item
		itemNode = this.document.createElement("li");
		itemNode.className = "toc-item";
		parent.appendChild(itemNode);

		linkNode = this.document.createElement("a");
		linkNode.className = "tc-tiddlylink";
		linkNode.setAttribute("href",`#${toc[i].anchor}`);
		itemNode.appendChild(linkNode);

		spanNode = this.document.createElement("span");
		spanNode.textContent = toc[i].text;
		linkNode.appendChild(spanNode);
	}
}

exports.toc = TocWidget;
})();